services:

  web:
    image: web
    build:
      context: ./web
    container_name: "web"
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - db
  db:
    image: mysql
    container_name: "sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_web
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789