services:

  web:
    image: web
    build:
      context: ./web
    container_name: "web"
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./web:/web  