# Generated by Django 5.0.6 on 2024-05-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('camara', models.CharField(max_length=200)),
                ('camaraFront', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('rom', models.CharField(max_length=200)),
                ('microUSB', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_payment', models.DateField()),
                ('method_payment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('star', models.IntegerField(default=0)),
                ('rateCount', models.IntegerField(default=0)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.detail')),
                ('promo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.promo')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOder',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('dateorder', models.DateField()),
                ('totalprice', models.CharField(max_length=200)),
                ('satatus_oder', models.CharField(max_length=200)),
                ('shippingid', models.CharField(max_length=200)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('comment', models.CharField(max_length=200)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
