services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3366:3306
    volumes:
      - web_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: my_web

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: my_web
      DB_USER: root
      DB_PASSWORD: 123456789

volumes:
  web_data: